### PR TITLE
Adding Carthage support by marking the scheme as Shared.

### PR DESCRIPTION
**Pull request by mrubin**
See https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

### CODE REVIEW

**Comment by Jitsusama** [comment]
Interesting. I have heard of Carthage, but never dug into it. I read over their GitHub page quickly and am just wondering about a few things.

First, is all that is required is to have a xcshareddata available on your GitHub project and Carthage will automagically build it when it is define in your projects Cartfile?

Second, will Carthage automatically build the library to match your application's target platform?

**Comment by mrubin** [comment]
> is all that is required is to have a xcshareddata available

Apparently so

> will Carthage automatically build the library to match your application's target platform?

Yes

I am making use of this change via Carthage and it has worked as expected.

**Comment by Jitsusama** [comment]
Groovy. I'll hopefully take a closer look tonight at this.

**Comment by Jitsusama** [comment]
Xcode is trying to make me give up. I've tried to test that Carthage will work with just the introduction of a shared build, but when I make a simple CLI app to include my library when built via Carthage (including a Cartfile pointing to a local git repo with the change present, running `cartage update` and then dragging the UInt128.framework file to `Linked Frameworks and Libraries`), I get a runtime linking error as so:

```
dyld: Library not loaded: @rpath/UInt128.framework/Versions/A/UInt128
  Referenced from: /Users/jitsusama/Library/Developer/Xcode/DerivedData/TestUInt128-bkjjngsxognslugbtpineupspnms/Build/Products/Release/TestUInt128
  Reason: image not found
Program ended with exit code: 9
```

I set `Always Embed Swift Standard Libraries` to `Yes` and I even set `Runtime Search Paths` to `$(inherited) @executable_path/../Frameworks @loader_path/Frameworks`, but it still is being a nasty face.

Have you tried this with any of your own applications against UInt128? If so, was there a magical Xcode invocation that was required to get it to work with a Carthage built Framework?

**Comment by Jitsusama** [comment]
Alright, I figured out that those issues were not related to UInt128, or the Carthage built products, and instead is just inanity involved with CLI programs and Swift.

**Comment by Jitsusama** [comment]
Thanks for the pull request! Having finally figured out how to test it, it looks great, so I've merged it in.

**Pull request merged**
