### PR TITLE
Swift Version 3.2/4.0 Support

### PR DESCRIPTION
**Pull request by Jitsusama**
This is a major restructuring and in certain places rewriting of the library. The Swift 3.2/4.0 UnsignedInteger changes are pretty massive at the protocol layers. I might end up rebasing this later, as a lot of source is ripped out in this version, but it was the only way I could
start making progress.

Skeletons for all required methods, protocols and tests should be present. Most of the tests currently fail, as a number of the stub methods needs to be fleshed out before most basic operation can work.

This work is started as part of issue #6, and the end goal is to resolve that ticket while also moving this library forward in regards to future Swift API compatibility.

### CODE REVIEW

**Comment by Jitsusama** [comment]
The upside of this work is that ultimately it looks like the Swift standard library has a lot of auto-generated methods which weren't there before, so my code can be drastically reduced. That said, a lot of the changes are not backwards compatible.

I'm going to start by working on Swift 3.2/4.0 support only, ripping out support for 3.1 and previous. Once I have this working, I will look at how difficult it will be to continue supporting older versions of Swift. I have some ideas on how I can do this, but I don't want to slow down my progress trying to tackle both problems at the same time.

**Comment by Jitsusama** [comment]
I wonder what in the world `dividingFullWidth(dividend: (high:low:))` is even supposed to do. Like, I understand it takes an existing value, uses it as the divisor, and takes a double width input in as the dividend, but, why, and what is the basic logic of how it works?

**Comment by Jitsusama** [comment]
This is fully working as far as I can tell. Extensive test coverage is present and all tests pass under both Swift 3.2 and Swift 4.0 mode.

**Comment by Jitsusama** [comment]
As far as I'm concerned, this work is now done. I'm not convinced of the wisdom in keeping newer versions compilable under Swift 3.1 and 3.2/4.0. Unless there is demand, once Swift 3.2/4.0 becomes GA, I will merge this code as in into master and tag a new release.

**Comment by adamnemecek** [comment]
You should merge this.

**Comment by Jitsusama** [comment]
@adamnemecek, thanks. I think I will, but only after the next version of Xcode goes stable. They keep on making minor changes to the API.

**Comment by lloydnewman** [comment]
Any updates on this @Jitsusama?

**Comment by Jitsusama** [comment]
@lloydnewman, not yet. I've been meaning to download the final release of Xcode and make sure that nothing has broken, that just hasn't happened yet.

**Comment by Jitsusama** [comment]
I've tested out the swift4.0 branch on Xcode 9.0 and its looking good, but the swift3.2 branch is complaining because of ArithmeticOverflow and some missing BinaryInteger stubs, so I think I'm just going to skip ahead to 4.0. Version 0.7.0 is now up based on the swift4.0 branch.

**Pull request closed without merging**
