### PR TITLE
Add scheme for iOS

### PR DESCRIPTION
**Pull request by guoxiaoqiao**
Related to issue https://github.com/Jitsusama/UInt128/issues/8

### CODE REVIEW

**Comment by guoxiaoqiao** [comment]
Because Xcode 8 is compatible with xcode 9 project file, I just Cherry-Pick from swift3.2 branch, and did not do any change.

**Comment by Jitsusama** [comment]
PR #9 contains history on this.

**Comment by Jitsusama** [comment]
I've done some playing around with Carthage, and it looks like no additional schemes are needed to build for other platforms. When I build my project locally, it builds all of the things automagically.

Take a look at this:

```
$ sudo xcode-select --switch ~/Downloads/Xcode-beta.app/Contents/Developer
$ carthage build --configuration release --no-skip-current
*** Please update to the latest Carthage version: 0.23.0. You currently are on 0.22.0
*** xcodebuild output can be found in /var/folders/q9/2lj11rv13zn4frc0_hcskl3w0000gn/T/carthage-xcodebuild.mtUQnr.log
*** Building scheme "UInt128" in UInt128.xcodeproj
$ tree -L 3 Carthage
Carthage
└── Build
    ├── Mac
    │   ├── UInt128.framework
    │   └── UInt128.framework.dSYM
    ├── iOS
    │   ├── 21AD4D15-F06C-30C9-A19C-8967F2F605CB.bcsymbolmap
    │   ├── UInt128.framework
    │   └── UInt128.framework.dSYM
    ├── tvOS
    │   ├── 3BDBAD30-09EF-389E-9CEE-9BEF67B6CA56.bcsymbolmap
    │   ├── UInt128.framework
    │   └── UInt128.framework.dSYM
    └── watchOS
        ├── 2F114CDE-E852-30CA-8797-587AE94A9131.bcsymbolmap
        ├── UInt128.framework
        └── UInt128.framework.dSYM

13 directories, 3 files
```

This was from the root of a clone of this project running on the swift3.2 branch, without any changes being made to my Xcode project.

I'm going to try from a project importing this one as a Cartfile to see if that changes things at all.

**Comment by Jitsusama** [comment]
@guoxiaoqiao; I've played around a bit and was able to get it to work with a Cartfile project that requires the swift3.2 branch from this repo. Using `xcode-select` to choose the beta version of Xcode 9, put a Cartfile like the following into your project's root folder:

```
git "Jitsusama/UInt128" "swift3.2"
```

Then, run `carthage bootstrap` from that same folder. It should build UInt128 into the `Carthage/Build` directory. You can add the framework file from that directory to your product's Linked Frameworks and Libraries and it should work fine.

The single shared build scheme that I have defined in the project right now is enough for Carthage to build an artifact for all architecture types. Unless there is something I'm missing, I don't think we'll need this PR, though I am thankful for you taking the time to make it.

Please let me know if I'm missing something important in my analysis.

**Comment by guoxiaoqiao** [comment]
https://github.com/guoxiaoqiao/uint128-test
I create a test project, can reproduce the https://github.com/Jitsusama/UInt128/issues/8 problem, you can checkout and try it.

**Comment by Jitsusama** [comment]
@guoxiaoqiao; thanks. Would you mind giving me the scenario that you reproduce the problem with? I want to make sure that I follow the same steps you are.

**Comment by guoxiaoqiao** [comment]
@Jitsusama Just set iOS Deployment Target param blow 11.0 will reproduce.
qq 20170624111745

**Comment by Jitsusama** [comment]
Thanks, I'll give that a shot.

**Comment by Jitsusama** [comment]
Strange, there must be something I'm doing differently.

Here's the commands I followed:

```
$ git clone https://github.com/guoxiaoqiao/uint128-test.git
$ cd uint128-test
$ rm Cartfile.resolved
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching UInt128
*** Checking out UInt128 at "d3f2ca01c60dbd3a63ce95e105ee192903bfd98e"
*** xcodebuild output can be found in /var/folders/q9/2lj11rv13zn4frc0_hcskl3w0000gn/T/carthage-xcodebuild.SLDRwg.log
*** Building scheme "UInt128" in UInt128.xcodeproj
$ tree -L 2 Carthage/Build
Carthage/Build
├── Mac
│   ├── UInt128.framework
│   └── UInt128.framework.dSYM
├── iOS
│   ├── D0B46570-9C1C-3B27-B0B4-52D0384CE312.bcsymbolmap
│   ├── UInt128.framework
│   └── UInt128.framework.dSYM
├── tvOS
│   ├── 118B5DF6-2786-3B0A-A7AF-CF865D35D95F.bcsymbolmap
│   ├── UInt128.framework
│   └── UInt128.framework.dSYM
└── watchOS
    ├── 5D9C7943-E3B2-3EBA-8506-B6A1056E6ECD.bcsymbolmap
    ├── UInt128.framework
    └── UInt128.framework.dSYM
$ open UInt128.xcodeproj
```

After the project opened, I verified that UInt128.framework was pointing to `./Carthage/Build/iOS/UInt128.framework`. I then went to the project settings, uint128-test target, and changed Deployment Target to 11.0 from 10.0. I was then able to build the project without issue. I did get an error when trying to launch it though. this is what it was:

    Error returned in reply: Connection invalid
    Software caused connection abort

I'm not sure if that's the error you're experiencing? I'm guessing it has to do with the hardware simulator not launching right.

Could you let me know if you followed different steps, or if you did the same thing but got a different error?

**Comment by Jitsusama** [comment]
I got that error to go away. I had to completely quit out of Xcode and relaunch. I'm guessing I still had it open from before I ran `xcode-select` against Xcode 9. When it launch I got a dyld error. Following the steps found on Carthage's [README](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos), I setup the project to copy over the framework upon running. That seems to have done the trick. I got the app to run without errors.

**Comment by guoxiaoqiao** [comment]
@Jitsusama Are you use Xcode 9? and Command line tools Set to 9.0?


qq 20170624115649

**Comment by Jitsusama** [comment]
Yes and yes. My iOS deployment target had to be set to iOS 11.0 or I got the error you are seeing though. I set the deployment on the target, not the project btw. Try clicking on uint128-test from underneath the targets heading and set the deployment target there.

**Comment by Jitsusama** [comment]
Here's my similar screenshot to what you shared:

screenshot

You can see in the top status bar that the application is running.

As well, below is a diff showing the project settings I got from your repository. Hopefully your problem is just some obscure project setting:

```diff
--- a/uint128-test.xcodeproj/project.pbxproj
+++ b/uint128-test.xcodeproj/project.pbxproj
@@ -86,6 +86,7 @@
 				16F84E8A1EFE048A00B04381 /* Sources */,
 				16F84E8B1EFE048A00B04381 /* Frameworks */,
 				16F84E8C1EFE048A00B04381 /* Resources */,
+				484D44251EFE1ABE00DB70F8 /* ShellScript */,
 			);
 			buildRules = (
 			);
@@ -108,6 +109,7 @@
 				TargetAttributes = {
 					16F84E8D1EFE048A00B04381 = {
 						CreatedOnToolsVersion = 9.0;
+						ProvisioningStyle = Manual;
 					};
 				};
 			};
@@ -142,6 +144,24 @@
 		};
 /* End PBXResourcesBuildPhase section */
 
+/* Begin PBXShellScriptBuildPhase section */
+		484D44251EFE1ABE00DB70F8 /* ShellScript */ = {
+			isa = PBXShellScriptBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+			);
+			inputPaths = (
+				"$(SRCROOT)/Carthage/Build/iOS/UInt128.framework",
+			);
+			outputPaths = (
+				"$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/UInt128.framework",
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+			shellPath = /bin/sh;
+			shellScript = "/usr/local/bin/carthage copy-frameworks";
+		};
+/* End PBXShellScriptBuildPhase section */
+
 /* Begin PBXSourcesBuildPhase section */
 		16F84E8A1EFE048A00B04381 /* Sources */ = {
 			isa = PBXSourcesBuildPhase;
@@ -281,15 +301,19 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-				DEVELOPMENT_TEAM = H2X2RB7XHH;
+				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
+				CODE_SIGN_STYLE = Manual;
+				DEVELOPMENT_TEAM = "";
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(PROJECT_DIR)/Carthage/Build/iOS",
 				);
 				INFOPLIST_FILE = "uint128-test/Info.plist";
+				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
 				PRODUCT_BUNDLE_IDENTIFIER = "net.test123.uint128-test";
 				PRODUCT_NAME = "$(TARGET_NAME)";
+				PROVISIONING_PROFILE_SPECIFIER = "";
 				SWIFT_VERSION = 4.0;
 				TARGETED_DEVICE_FAMILY = "1,2";
 			};
@@ -299,15 +323,19 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
-				DEVELOPMENT_TEAM = H2X2RB7XHH;
+				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
+				CODE_SIGN_STYLE = Manual;
+				DEVELOPMENT_TEAM = "";
 				FRAMEWORK_SEARCH_PATHS = (
 					"$(inherited)",
 					"$(PROJECT_DIR)/Carthage/Build/iOS",
 				);
 				INFOPLIST_FILE = "uint128-test/Info.plist";
+				IPHONEOS_DEPLOYMENT_TARGET = 11.0;
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
 				PRODUCT_BUNDLE_IDENTIFIER = "net.test123.uint128-test";
 				PRODUCT_NAME = "$(TARGET_NAME)";
+				PROVISIONING_PROFILE_SPECIFIER = "";
 				SWIFT_VERSION = 4.0;
 				TARGETED_DEVICE_FAMILY = "1,2";
 			};
```

**Comment by guoxiaoqiao** [comment]
@Jitsusama I know this setting can run in simulator, If you have a iOS device, you can try it, It cannot install.

**Comment by Jitsusama** [comment]
Ah, ok, that is good to know. I'm heading to bed now, but I'll try and reproduce this on my iPad sometime this weekend.

**Comment by guoxiaoqiao** [comment]
Okay, good night.

**Comment by Jitsusama** [comment]
Oh drat, I can't anyways, I have to be running iOS 11. Do you have a device actually running iOS 11?

**Comment by guoxiaoqiao** [comment]
My device running 10.3.2, I believe it can run on iOS 11 device, but always have some people not install the latest iOS system

**Comment by Jitsusama** [comment]
As far as I'm aware Swift 3.2/4.0 can only run on iOS 11 devices. When you set your deployment target to 11.0, it means you will only deploy it on those releases. Here's what Xcode shows when I try to select a non iOS 11 device (and yes, I'm still not in bed, bad me! 😉):

screenshot

**Comment by Jitsusama** [comment]
Ok, so if I set my deployment target version lower than 11.0, neither Simulator or legitimate devices work, as Carthage builds UInt128 for 11.0. I can't figure out a way to get Carthage to choose a lower target platform version. This might be an issue with Carthage itself, but I can't say that for certain. Are you aware of a way to force Carthage to build against a different target platform?

**Comment by Jitsusama** [comment]
This is the error I get btw:

```
Module file's minimum deployment target is ios11.0 v11.0: /Users/jitsusama/Downloads/Git-Repos/uint128-test/Carthage/Build/iOS/UInt128.framework/Modules/UInt128.swiftmodule/arm64.swiftmodule
```

**Comment by guoxiaoqiao** [comment]
This is how I open this merge request, I just know multiple scheme can resolve this problem current.

**Comment by guoxiaoqiao** [comment]
And my merge request not contain tvOS and watchOS scheme.

**Comment by Jitsusama** [comment]
Thanks @guoxiaoqiao for the additional information. I think I'm starting to understand things better now. I'll take another look later this weekend.

**Comment by Jitsusama** [comment]
Alright, I've found this StackOverflow [question](https://stackoverflow.com/questions/40952678/select-deployment-target-for-carthage-dependency) which points to this Carthage [issue](https://github.com/Carthage/Carthage/issues/1629). It appears that Carthage will try to use the target's deployment target if it can, but if it cannot, it looks like it will default to some value, which might be the highest target platform that Xcode can support.

I'm guessing there is a bug here, as your project's default target platform would ideally be picked up by Carthage when building dependencies. That said, I can see why it might be desirable to just have those shared schemes available in the upstream project for situations such as yours.

I'm going to take a closer look at your branch, but I'm thinking I'll probably merge it and then add the missing target schemes myself. It will make building UInt128 a bit more confusing, but I think this use-case probably merits this.

It makes me quite sad that the SPM does not support any platform except for macOS/Linux. I created the newer UInt128.xcodeproj from SPM hoping that it would increase simplicity rather than break it.

**Comment by guoxiaoqiao** [comment]
I don't think this is a Carthage problem,  The root cause is that a target in the Xcode project desgined for corresponds to only one OS platform (iOS or macOS, watchOS, tvOS),  of course, Xcode allows settings to correspond to multiple platforms, but I think there will be a lot of problems, just like problems now encountered.

**Comment by Jitsusama** [comment]
@guoxiaoqiao, you are correct. I finally figured out what the key piece is. The minimum deployment target is derived from the target's deployment platform. When a particular platform does not have a target, Xcode defaults to the highest version of platform available. In your deployment target, you set the deployment platform to iOS 8.0, and this is what fixes the issue for you.

I had never thought about this possibility before, but I do believe it's important. With this in mind, I am going to merge this pull request. I will add the other target platforms as well on my own so we'll have all of our bases covered.

The only reason I can get away with this is because I've avoided Foundation altogether. If I hadn't, we probably wouldn't be able to target a platform as old as this, as Swift doesn't include all of Foundation.

Thanks so much for this pull request, and sorry I took so long merging it. If you can't tell, I'm a bit picky and require understanding before merging. Thanks for putting up with it!

**Pull request merged**
