### PR TITLE
:Codable

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by Jitsusama** [comment]
Hello @adamnemecek, thanks for your code!

Before adding this to the code-base, I would like to see a set of tests that cover this new functionality. Would you mind adding this to your PR? Tests that reflect how this protocol might actually be used by a user would be very nice, and any boundary conditions that you think would make sense.

**Comment by adamnemecek** [comment]
Note that all the basic types (like UInt64) conform to that protocol and the semantics of this are very expectable. I will add a simple test. However, I believe the user can figure out how to use this from the documentation on codable https://developer.apple.com/documentation/swift/codable.

**Comment by Jitsusama** [comment]
My reasons for the tests requested is not to act like documentation, but rather, to ensure that the functionality works from the standpoint of when the API is called directly through the methods provided, or when it is called indirectly via mechanisms afforded by Swift. For example, string to UInt128 conversions can happen through a variety of methods. I’ve found that when changes are introduced to Swift, our API May continue to work while the way Swift interacts with our API can become broken.

**Comment by adamnemecek** [comment]
Ah ok. Is this enough?

**Comment by Jitsusama** [comment]
I think so. It looks like by utilizing the JSON encoder/decoder that our API is being tested indirectly, which is probably the safest way to validate that the Swift API is working well with our own. I guess the only question I have for you is whether this test is enough to make you feel safe that when it passes, it means that our Codable interface is 100% AOK?

**Comment by adamnemecek** [comment]
Like there isn't much that can be broken. I don't understand the linux tests, e.g. where is UInt128BitwiseOperationsTests defined?

**Comment by Jitsusama** [comment]
@adamnemecek; nevermind then. It looks like I haven't paid proper attention to that file either, as I'm pretty sure it's broken. On Linux systems, the Xcode test runner isn't present, so `LinuxMain.swift` is used to replace it. If you're comfortable with the tests, I think I am as well. Worse case, if an issue arises in the future, we can add tests to cover that situation then.

**Comment by Jitsusama** [comment]
Thanks for submitting this code!

**Comment by adamnemecek** [comment]
no prob.

**Pull request merged**
