### PR TITLE
Add scheme for iOS

### PR DESCRIPTION
**Pull request by guoxiaoqiao**

### CODE REVIEW

**Comment by Jitsusama** [comment]
Thanks for this pull request! This has bothered me as well. The reason I didn't have it up anymore (I used to have a defined universal build scheme which used a script to build each target platform from a single scheme), is because I was trying to use SPM to create my Xcode project.

With this in mind, do you know of a way to do this with the SPM? Is that what you used to create the files in this PR?

**Comment by Jitsusama** [comment]
Also, I'm assuming that this PR is related to issue #8, is that correct?

**Comment by guoxiaoqiao** [comment]
@Jitsusama Yes, It is related to issue https://github.com/Jitsusama/UInt128/issues/8

**Comment by guoxiaoqiao** [comment]
@Jitsusama I create this PR use Xcode 9, and I'm not familiar with SPM. I found one target can only correspond to one SDK, so haven't found a way to use universal scheme.

**Comment by Jitsusama** [comment]
@guoxiaoqiao; how are you including UInt128 in your own projects? Via SPM, Carthage, CocoaPods, some other dependency manager, adding this repo manually into your project workspace, or by copying over the UInt128.swift file over manually?

**Comment by guoxiaoqiao** [comment]
@Jitsusama I'm trying to use Carthage, because other framework in my project is use Carthage.

**Comment by Jitsusama** [comment]
@guoxiaoqiao, thanks for that information. This evening I'll take a look at how your change will work with the other package managers, and particularly with Carthage in different build environments. If everything looks good, I'll probably merge it in to master and then rebase this branch off of master to incorporate it.

**Comment by Jitsusama** [comment]
Oh, if I decide to merge to master first, I might need you to rework this change on top of master instead of swift3.2.

**Comment by guoxiaoqiao** [comment]
@Jitsusama OK, I will do it now. merge or not, I respect your decision

**Comment by Jitsusama** [comment]
Thanks! I'll close this and refer to it from the new PR.

**Pull request closed without merging**
